export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',


    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    SET_TOKEN: "SET_TOKEN",
}

export const TeacherConstants = {
    GET_TEACHER_REQUEST: ' GET_TEACHER_REQUEST',
    GET_TEACHER_SUCCESS: ' GET_TEACHER_SUCCESS',
    GET_TEACHER_FAILURE: ' GET_TEACHER_FAILURE',

    GET_DEPARMENT_TEACHER_REQUEST: 'GET_DEPARMENT_TEACHER_REQUEST',
    GET_DEPARMENT_TEACHER_SUCCESS: 'GET_DEPARMENT_TEACHER_SUCCESS',
    GET_DEPARMENT_TEACHER_FAILURE: 'GET_DEPARMENT_TEACHER_FAILURE',

    GET_TEACHER_DETAIL_REQUEST: 'GET_TEACHER_DETAIL_REQUEST',
    GET_TEACHER_DETAIL_SUCCESS: 'GET_TEACHER_DETAIL_SUCCESS',
    GET_TEACHER_DETAIL_FAILURE: 'GET_TEACHER_DETAIL_FAILURE',
}

export const StudentConstants = {
    STUDENT_SIGNUP_REQUEST: "STUDENT_SIGNUP_REQUEST",
    STUDENT_SIGNUP_SUCCESS: "STUDENT_SIGNUP_SUCCESS",
    STUDENT_SIGNUP_FAILURE: "STUDENT_SIGNUP_FAILURE",

    STUDENT_LOGIN_REQUEST: "STUDENT_LOGIN_REQUEST",
    STUDENT_LOGIN_SUCCESS: "STUDENT_LOGIN_SUCCESS",
    STUDENT_LOGIN_FAILURE: "STUDENT_LOGIN_FAILURE",
}


export const AddStudentCourseConstants = {
    ADD_COURSE_REQUEST: "ADD_COURSE_REQUEST",
    ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
    ADD_COURSE_FAILURE: "ADD_COURSE_FAILURE",

    GET_COURSE_REQUEST: "GET_COURSE_REQUEST",
    GET_COURSE_SUCCESS: "GET_COURSE_SUCCESS",
    GET_COURSE_FAILURE: "GET_COURSE_FAILURE",

}

export const ClassLectureConstants = {
    GET_CLASSLECTURE_REQUEST: "GET_CLASSLECTURE_REQUEST",
    GET_CLASSLECTURE_SUCCESS: "GET_CLASSLECTURE_SUCCESS",
    GET_CLASSLECTURE_FAILURE: "GET_CLASSLECTURE_FAILURE",
}

export const ResultConstants = {
    GET_RESULT_REQUEST: "GET_RESULT_REQUEST",
    GET_RESULT_SUCCESS: "GET_RESULT_SUCCESS",
    GET_RESULT_FAILURE: "GET_RESULT_FAILURE",
}
